### ISSUE TITLE
Typing long text make a weird bug.

### ISSUE THREAD

**Issue by Dan1jel** [arbourd/prompt#3]
Don't know if it's my app (termux) or if it's fish (or maybe both) but do you maybe know why this is happening? I edit the colors and made the right prompt bold. [(See video)](http://imgur.com/a/LaCNgxH)

Thanks for fixing the other bug btw.

**Comment by arbourd** [comment]
You're welcome. 🙂 That link is 404ing for me. I know you can upload gifs/mp4s/movs here in the comments.

**Comment by Dan1jel** [comment]
> You're welcome. 🙂 That link is 404ing for me. I know you can upload gifs/mp4s/movs here in the comments.

Weird, i change the URL so it should work now, but just in case, i post it here also :)  i tried to see where I could upload but i only see "photos" as an option :/ 

http://imgur.com/a/LaCNgxH

**Comment by arbourd** [comment]
Not sure what the issue is in the video. Could you help me understand what you see as the bug?

Also, if the issue is the replacing of the branch name / commit, that is part of fish-shell.

![Kapture 2021-01-03 at 13 46 50](https://user-images.githubusercontent.com/7211830/103486566-b62cf980-4dcc-11eb-88e5-d1ab5bf017c5.gif)

**Comment by Dan1jel** [comment]
Sure sorry for my lack of information.

I use termux, an Android app linux shell that I use fish in, and when I type alot of text that don't fit the with of the screen, all the symbols jump back one line. You could see it right next to the $ symbol. 

But i think it might have something to with termux and fish.

**Comment by arbourd** [comment]
No need to appologize.

Ya I think so. Because this little project just draws the text on the left and the right. I haven't seen that problem on macOS nor Ubuntu so I'm guessing it's probably how the terminal emulator redraws the lines.

If you find anything specific to this project tho, please don't hesitate for commenting. Thanks for bringing up these issues.

**Comment by Dan1jel** [comment]
Sure thing. Thanks for updating and all quick reply. If i do find out anything i let you know. Have a great 2021 and take care!
